# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

def pods_for_dev
  pod 'AFNetworking', '~> 2.4'
  pod 'JSONModel', '~> 1.0'
end

def pods_for_test
  pod 'Expecta', '~> 0.3'
end  

target "coffee" do
  pods_for_dev
end

target "coffeeTests" do
  pods_for_dev
  pods_for_test
end

post_install do |installer|
  File.open("#{installer.sandbox_root}/Headers/module.map", 'w') do |fp|
    installer.pods.each do |pod|
      normalized_pod_name = pod.name.gsub('-', '')
      fp.write <<EOF
module #{normalized_pod_name} [system] {
  umbrella "#{pod.name}"
  export *
}
EOF
      puts "Generating Swift Module #{normalized_pod_name.green} for #{pod} OK!"
    end
  end
end